### ISSUE TITLE
Edit buttons for all products

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#122]
### Tasks

- [ ] Create EditCpuCooler and it works without error
- [ ] Create EditDrive and it works without error
- [ ] Create EditGpue and it works without error
- [ ] Create EditMotherBoard and it works without error
- [ ] Create EditPcCase and it works without error
- [ ] Create EditPsu and it works without error
- [ ] Create EditRam and it works without error
