### ISSUE TITLE
Authentication and Authorization Backend

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#127]
#### Tasks : 
- [x] Setting up Identity
- [x] Adding the Identity configuration and seed
- [x] Creating AccountController
- [x] Create User roles(static class)
- [x] Create Login and Register endpoints
- [x] Testing the Login and Register methods

(Policy and claim)

#### JWT token :
- [x] Creating JWT token service
- [x] Validating JWT token on server
