### ISSUE TITLE
Authentication and Authorization Frontend

### ISSUE THREAD

**Issue by Barna95** [Eriknpy/Compute-yourself#129]
#### Tasks:

- [x] Create Login/Register route
- [x] Save token to localStorage or cookie
- [x] Show if user is logged in in navbar
