### ISSUE TITLE
Implement View/Controller/Service for GPU

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#5]
### Tasks:
- [x] Inherit from BaseService
- [x] Add interface _(e.g: IGPUService)_
- [x] Add endpoints in Controller
- [x] Create views for the endpoints
- [x] Add bootstrap style

**Comment by Eriknpy** [comment]
### Tasks:
- [ ] Inherit from BaseService
- [ ] Add interface _(e.g: IGPUService)_
- [ ] Add endpoints in Controller
- [ ] Create views for the endpoints
- [ ] Add bootstrap style
