### ISSUE TITLE
Rework controllers

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#66]
### Tasks
- [x] Restructure old controllers
- [x] Create Products controller
- [x] Test endpoints with Postman
