### ISSUE TITLE
Rework enums & Base product & Seed

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#67]
### Tasks

**Rework enums**

- [x] Sort all not future proof enums
- [x] Set the excluded ones to string

**Rework base product class**

- [x]  Add productOfficialWebsite property
- [x]  Add mainImage property
- [x]  Add SerialNumber
- [x]  Remove Unnecessary JsonStringEnumConverter annotations

**Update Seed**

- [x]  Set recently added properties
- [x]  Replace PCX links with official page url
- [x]  Update direct product images
- [x]  Set price to foreign currency
