### ISSUE TITLE
Implement View/Controller/Service for RAM

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#7]
### Tasks:
- [x] Inherit from BaseService
- [x] Add interface _(e.g: IGPUService)_
- [x] Add endpoints in Controller
- [x] Create views for the endpoints
- [x] Add bootstrap style
