### ISSUE TITLE
Setup frontend

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#72]
### Tasks

- [x]  Setup Cors
- [x]  Setup React based on [Vite ](https://vitejs.dev/)template
- [x]  Extend gitignore with npm package folder
- [x]  Write the first fetch towards our backend
- [x]  Preferably use Axios
