### ISSUE TITLE
Generalise Product controller

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#73]
### Tasks

- [x]  Create BaseController which includes CRUD
- [x]  Create controllers for all PC parts
- [x]  Extends BaseController
- [x]  Test Get endpoints
- [x]  Test Post endpoints
- [x]  Test Put endpoints
- [x]  Test Delete endpoints
