### ISSUE TITLE
React routing

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/Compute-yourself#76]
### Tasks

- [x] Use createBrowserRouter
- [x] Use Navlink instead of link
- [x] Have a layout
- [x] Basic css with declared colors
- [x] Use Outlet at layout
- [x] [Documentation](https://reactrouter.com/en/main)
